USE [master]
GO

/****** Object:  Database [PLANE_TICKET]    Script Date: 5/21/2021 5:28:31 AM ******/
CREATE DATABASE [PLANE_TICKET] ON  PRIMARY 
( NAME = N'PLANE_TICKET', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLBOS\MSSQL\DATA\PLANE_TICKET.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PLANE_TICKET_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLBOS\MSSQL\DATA\PLANE_TICKET_log.LDF' , SIZE = 576KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PLANE_TICKET].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PLANE_TICKET] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PLANE_TICKET] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PLANE_TICKET] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PLANE_TICKET] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PLANE_TICKET] SET ARITHABORT OFF 
GO

ALTER DATABASE [PLANE_TICKET] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [PLANE_TICKET] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PLANE_TICKET] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PLANE_TICKET] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PLANE_TICKET] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PLANE_TICKET] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PLANE_TICKET] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PLANE_TICKET] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PLANE_TICKET] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PLANE_TICKET] SET  ENABLE_BROKER 
GO

ALTER DATABASE [PLANE_TICKET] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PLANE_TICKET] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PLANE_TICKET] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PLANE_TICKET] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PLANE_TICKET] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PLANE_TICKET] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PLANE_TICKET] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PLANE_TICKET] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PLANE_TICKET] SET  MULTI_USER 
GO

ALTER DATABASE [PLANE_TICKET] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PLANE_TICKET] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PLANE_TICKET] SET  READ_WRITE 
GO

